spring:
  datasource:
    url: jdbc:h2:mem:budget-planner
    username: user
    password: pw
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  request:
    includeQueryString: true
    includePayload: true
    includeHeaders: false
    maxPayloadLength: 2000
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
